### ISSUE TITLE
Some users on the database don't have initials

### ISSUE THREAD

**Issue by dylanramos** [CPNV-ES/larasta#133]
Some users on the database don't have initials, this issue causes exceptions when making a new remark.

**Comment by dylanramos** [comment]
I changed the column author of the remarks table into a foreign key pointing on the people table.
**DATA IN THE AUTHOR COLUMN MUST BE UPDATED**

**Comment by dylanramos** [comment]
The author column from the remark table should be a foreign key pointing in the people table

**Comment by dylanramos** [comment]
Fixed but could be better.
https://github.com/CPNV-ES/larasta/commit/c1bcfc6f64f286789ae5ad056ecfed2c13c6840e

**Comment by imfeldd** [comment]
You could use an [accessor](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor) to dynamically generate initials for Persons that don't have one in the DB
```php
// ... in Person.php
public function getInitialsAttribute($value) {
   return $value === null ? $this->fullName : $value;
}
```

Then you can still get the initials with ``Person->initials``, and for Persons without initials it will return their full name.

**Comment by dylanramos** [comment]
Solved https://github.com/CPNV-ES/larasta/issues/133#issuecomment-844897586
